development:
  adapter: postgresql
  database: tfl_development
  pool: 5
  username: bmetzger
  host: localhost

test:
  adapter: postgresql
  database: tfl_test
  pool: 5
  username: bmetzger
  host:  localhost

production:
  adapter: postgresql
  database: tfl_production
  pool: 5
  username: bmetzger
  host:  localhost
